In [3]:
import scipy
import numpy as np
from sklearn import datasets
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris = datasets.load_iris()
iris_X = iris.data
iris_Y = iris.target

print(iris_X[:2,:])
print(iris_Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


上面代码完成了数据的加载，并且得到了数据集iris_X，以及其类别iris_Y（可以看出类别有三种）

In [2]:
X_train,X_test,Y_train,Y_test = train_test_split(iris_X,iris_Y,test_size=0.3)

In [8]:
Y_train,Y_test

(array([1, 0, 2, 2, 2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1,
        2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 1, 0,
        2, 2, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 2, 2, 2, 1, 1, 2, 0, 1, 1,
        2, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 0, 1, 1, 2, 1, 2, 1, 2,
        1, 2, 0, 1, 1, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 2, 2]),
 array([0, 1, 1, 1, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 1, 2, 2, 1,
        0, 0, 1, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 2, 1, 2, 2, 1, 1, 0, 1,
        2]))

这步操作打乱了数据的顺序，使其更贴近于真实情况的数据

In [11]:
knn = KNeighborsClassifier()
knn.fit(X_train,Y_train)
print(knn.predict(X_test))
print(Y_test)

[0 1 1 1 0 2 0 2 1 2 1 0 0 1 0 0 1 0 1 2 2 1 0 0 1 1 1 2 2 0 1 1 2 0 1 1 2
 1 2 2 1 1 0 1 2]
[0 1 1 1 0 2 0 2 1 2 2 0 0 1 0 0 1 0 1 2 2 1 0 0 1 1 1 2 2 0 1 1 2 0 1 2 2
 1 2 2 1 1 0 1 2]


上面代码展示了knn函数的工作过程，分为train和test两步，从结果中可以看出结果预测还是有错误情况